name: Keep Streamlit Alive
on:
  schedule:
    - cron: '0 * * * *' # Chạy đúng vào phút thứ 0 của mỗi giờ
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        # THAY LINK APP THỰC TẾ CỦA SẾP VÀO ĐÂY
        run: curl -I https://tailieuhopbtgdv.streamlit.app/
