name: Keep Streamlit Alive
on:
  schedule:
    - cron: '0 0 */1 * *' # Chạy mỗi 1 ngày một lần cho chắc ăn
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        # 👇 BẠN THAY ĐƯỜNG LINK BÊN DƯỚI THÀNH LINK APP STREAMLIT CỦA BẠN NHÉ 👇
        run: curl -I https://tailieuhopbtgdv.streamlit.app/
